### ISSUE TITLE
Sharepoint server  - search results in eweb don't have correct URLs

### ISSUE THREAD

**Issue by DianaJourdan** [elastic/enterprise-search-sharepoint-server-connector#36]
## Describe the bug
Search results in eweb don't have correct URLs but point to the localhost when testing locally (because they aren't absolute).

### To Reproduce
1. Create and set up the `Sharepoint Server` source
2. Do the full index
3. Set up the `Source` -> `Schema` and make the `created_at` be a date (to force schema save).
4. Go to the search page and search for content.
5. Open the preview on one search result and click through the URL.

## Expected behavior
* It should open the correct page. But it tries to open the page relative to localhost and goes into a 404.

## Additional context
Investigation shows that the indexed documents look as follows:

```json
{
      "type" : "list",
      "created_at" : "2022-01-24T13:21:10Z",
      "relative_url" : "/sites/Workplace",
      "title" : "Content type publishing error log",
      "url" : "/sites/Workplace/Lists/Content type publishing error log",
      "source" : "custom",
      "content_source_id" : "624ae08c6c66f7c4e6866a4c",
      "updated_at" : "2022-04-04T13:11:18+00:00",
      "last_updated" : "2022-04-04T13:11:14+00:00",
      "id" : "e24e5f96-8d3e-4472-b4fd-447aa6ef9fcb"
}      
```

The search results display was configured like this:

<img width="1291" alt="Screenshot 2022-04-04 at 17 23 10" src="https://user-images.githubusercontent.com/538843/161581020-3e6d7b66-cbe5-491f-8b26-32072cb20873.png">
<hr>
<img width="1283" alt="Screenshot 2022-04-04 at 17 20 16" src="https://user-images.githubusercontent.com/538843/161581076-72aeba6d-2bc2-47d4-a0a0-1da6f9b0003b.png">

## Screenshots
The attempt to follow the link leads to a 404:
<img width="1249" alt="Screenshot 2022-04-04 at 17 42 47" src="https://user-images.githubusercontent.com/538843/161581352-fc1fab09-a840-4c81-a8b7-c4d426e7a683.png">

**Comment by nirav-elastic** [comment]
This issue is same as https://github.com/elastic/enterprise-search-sharepoint-server-connector/issues/37. The reason for this is the base url from the endpoints are missing and hence, it redirects to localhost by default. The fix for this is already present in the outstanding PR: https://github.com/elastic/enterprise-search-sharepoint-server-connector/pull/30/files

**Comment by serenachou** [comment]
@DianaJourdan we may want to have another pass at re-testing this so we can formally close this out.

**Comment by prashant-elastic** [comment]
@serenachou The base URL is fixed now and it redirects to the correct URL. We have tested it and it works fine. Please find attached screenshots for your reference.

![BaseURLIssue#36](https://user-images.githubusercontent.com/103035276/164443508-e0f3dc8d-0c2b-4754-a79a-d8f35e6c480d.png)
<img width="1440" alt="Issue#36-Redirecting to the correct URL" src="https://user-images.githubusercontent.com/103035276/164443517-9dc1f021-9715-4be8-bc5b-91fe7e12edf8.png">
