### ISSUE TITLE
Sharepoint Server - search result tiles have no URLs by default

### ISSUE THREAD

**Issue by serenachou** [elastic/enterprise-search-sharepoint-server-connector#37]
## Describe the bug
When searching across the `Sharepoint Server` source, the results displayed aren't useful because they seem to be missing URLs.

### To Reproduce
1. Create and set up the `Sharepoint Server` source
2. Go to search page and find some `Sharepoint Server` source pages
3. Open the preview on one result

## Expected behavior
* A clickable link to the source page should be present. But it's not.
* A create date should be there and properly formatted. But it's not.

## Screenshots
<img width="1729" alt="Screenshot 2022-04-04 at 17 09 54" src="https://user-images.githubusercontent.com/538843/161575615-5ce056bc-8acd-4905-b312-33fc5429a5ea.png">

## Additional context

* The clickable URLs and the dates do appear in search results when the user goes into the `Source` -> `Schema` and sets the type of the date to `Date`, and then saved the schema.
* I also went to `Search` -> Display settings and check the URL field to be `url` but it was already preselected. I think what did it was just saving the explicit schema.

**Comment by nirav-elastic** [comment]
@serenachou , This is because the base url from the endpoints is missing and hence, it redirects to localhost by default. The fix for this is already present in the outstanding PR: https://github.com/elastic/enterprise-search-sharepoint-server-connector/pull/30/files

**Comment by serenachou** [comment]
copied this over to the original ticket for the team to see and retest

**Comment by prashant-elastic** [comment]
@serenachou This issue has been fixed and we have tested it. It looks fine now. Please find the screenshot attached for your reference.

![FixedIssue#37](https://user-images.githubusercontent.com/103035276/164443796-72ddd37d-89f4-4feb-9a78-dc21ab507d76.png)

**Comment by nirav-elastic** [comment]
Closing this since the issues has been fixed and merged into the main branch.
