### ISSUE TITLE
Sharepoint Server - icons and connectors aren't consistent

### ISSUE THREAD

**Issue by serenachou** [elastic/enterprise-search-sharepoint-server-connector#38]
## Describe the bug
The connector names and icons aren't consistent on source create page, sources list page, and the settings -> connectors page.

### To Reproduce
1. Create and set up the `Sharepoint Server` source via `Sources` -> `Add an organization content source`
2. Click on `Settings` -> `Connectors` and look for the `Sharepoint Server`
3. It's not there, but there's a `Sharepoint Online Connector package` instead, but it's not the same since its documentation points to https://www.elastic.co/guide/en/workplace-search/8.2/sharepoint-online-external.html and not to https://www.elastic.co/guide/en/workplace-search/8.2/sharepoint-server.html which is the documentation that `Sharepoint Server` points to
4. Go to the `Sources` page and look at the created `Sharepoint Server` source - its icon is of the `Custom` connector and not of the `Sharepoint Online` or `Sharepoint Server`

## Expected behavior
* The `Sources` -> Add connectors list should coincide with the `Settings` -> `Connectors` list
* The icons should also be matching

### Sources page
<img width="631" alt="Screenshot 2022-04-04 at 16 43 04" src="https://user-images.githubusercontent.com/538843/161570700-72595fe0-1630-41a4-ac50-63d3e5313588.png">

### Sources -> Add
<img width="1779" alt="Screenshot 2022-04-04 at 16 40 07" src="https://user-images.githubusercontent.com/538843/161570755-bba169df-c3c6-4831-9d77-59bb0f1c494b.png">

### Settings -> Connectors
<img width="1774" alt="Screenshot 2022-04-04 at 16 52 23" src="https://user-images.githubusercontent.com/538843/161571001-4e059876-1af0-453e-ba48-fc5c13d231b2.png">

**Comment by nirav-elastic** [comment]
We've a few queries regarding adding icon to the custom content source using REST APIs and would like to get some help from the Elastic Team Members.

1. Tried the /icon API endpoint specified in the official documentation (https://www.elastic.co/guide/en/workplace-search/current/workplace-search-content-sources-api.html#upload-content-source-icon-api) and the response was successful. However the icon indexed is only updated in the search page of the Enterprise Search but not in the content source page. 

2. Is there any standard dimensions defined for the content source icons ?

**Comment by serenachou** [comment]
@zombieFox do you happen to know what dimensions we typically provide for icons? FYI @artem-shelkovnikov

**Comment by zombieFox** [comment]
Icons are served as SVG, and I believe the icon size is defined by the `size` prop. eg: [`<SourceIcon serviceType={serviceType} name={name} size="xxl" />`](https://github.com/elastic/kibana/blob/8afa2c30fddc1ecbd1173311d4976c8c2ee9528c/x-pack/plugins/enterprise_search/public/applications/workplace_search/views/content_sources/components/add_source/configured_sources_list.tsx#L110). We use sizes from `xs` all the way to `xxl`.

**Comment by serenachou** [comment]
@nirav-elastic are you able to move forward with Kuldeeps latest guidance?

**Comment by nirav-elastic** [comment]
@zombieFox , @serenachou , I've a few questions here:

1. We're going to use API calls to upload an icon from the Python connector. Is that understanding right?
2. The API docs mention that the icon format must be in PNG. Reference: https://www.elastic.co/guide/en/workplace-search/current/workplace-search-content-sources-api.html#upload-content-source-icon-api
3. If the understanding of using API calls to upload the icon is right, then the follow-up question is: `Tried the /icon API endpoint specified in the official documentation (https://www.elastic.co/guide/en/workplace-search/current/workplace-search-content-sources-api.html#upload-content-source-icon-api) and the response was successful. However the icon indexed is only updated in the search page of the Enterprise Search but not in the content source page.`

**Comment by serenachou** [comment]
Closing this for now, after reviewing this, as there is a different icon associated with the content source, and the customer can choose to override the default one in the API with their desired one.
