### ISSUE TITLE
Should SharePoint in Microsoft 365 be listed under SharePoint Server compatibility?

### ISSUE THREAD

**Issue by catmanjan** [elastic/enterprise-search-sharepoint-server-connector#44]
2013, 2016 and 2019 Sharepoint server are listed as supported, but Sharepoint in Microsoft 365 is not (AKA the SAAS)

Judging by the rest of the doco I believe this is just an oversight

**Comment by serenachou** [comment]
Hey there @catmanjan actually SharePoint Online is covered by a different connector, one that an OOTB experience (https://www.elastic.co/guide/en/workplace-search/current/workplace-search-sharepoint-online-connector.html) and one that is customizable in 8.2 https://www.elastic.co/guide/en/workplace-search/8.2/sharepoint-online-external.html  I'd love to get your feedback on these connectors as you work through them!

**Comment by catmanjan** [comment]
Ah okay, I think this needs to be clearer in the readme, it says at the top that the connector is for “Microsoft 365 SharePoint Server” but Microsoft 365 is the SaaS brand
