### ISSUE TITLE
make test_connectivity Sharepoint test fails

### ISSUE THREAD

**Issue by catmanjan** [elastic/enterprise-search-sharepoint-server-connector#46]
I can see in Fiddler a request going to http://mytenant.australiasoutheast.cloudapp.azure.com///sites/spfarm/_api/web/webs?&$skip=0&$top=5000 

But this URL 404s

If I change the test to go to http://mytenant.australiasoutheast.cloudapp.azure.com//_api/web/webs?&$skip=0&$top=5000 instead the test passes

Is the test wrong or is my Sharepoint configuration?

**Comment by catmanjan** [comment]
I found this https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/determine-sharepoint-rest-service-endpoint-uris?tabs=csom

Not sure if this is the same REST API that is being used here, but it seems to imply that the /sites/ prefix isn't necessary?

![image](https://user-images.githubusercontent.com/137350/166174139-55374b1c-af12-48d4-98ef-15d6bec8fe3d.png)

**Comment by praveen-elastic** [comment]
Hey @catmanjan, the /sites/ prefix is optional only while creating the first site-collection in the web app. For all the later site-collections, the /sites prefix becomes mandatory. I have attached 2 screenshots below highlighting these two points. 

![image](https://user-images.githubusercontent.com/90465691/166224684-236d19a7-afbe-459a-86f8-3a17d053d14f.png)

![image](https://user-images.githubusercontent.com/90465691/166224664-3b0d23b5-4631-44e9-9c7d-77158f64984c.png)

Can you please confirm which of the 2 options did you choose while creating the site-collection ? Currently,  we recommend creating site-collections with /sites prefix for first collection too.
If possible, can you share your yml config you've used after removing the sensitive credentials.

**Comment by catmanjan** [comment]
Not sure if Site Collections were renamed or if I'm looking in the wrong place, but it seems there is no more /sites/ prefix when creating a site

![image](https://user-images.githubusercontent.com/137350/166341820-0f787717-7e2a-4eba-9523-50d88a678af3.png)

**Comment by praveen-elastic** [comment]
I think what you are referring to is settings for Sites and not Site Collection. Site-collections are created from central admin page: it has a url ending with `_admin/createsite.aspx` .

**Comment by catmanjan** [comment]
Ah I see, so just to confirm the connector has a limitation that it can’t index the top level site collection, or a site collection that hasn’t got the /sites/ prefix?

**Comment by praveen-elastic** [comment]
Correct, the connector won't be able to index site collection that hasn’t got the /sites/ prefix.
