### ISSUE TITLE
What determines whether user gets Connector Owners permission?

### ISSUE THREAD

**Issue by catmanjan** [elastic/enterprise-search-sharepoint-server-connector#50]
I've just noticed that all my users have the Connectors Owners permission (and only this permission) which seems to be in the _allow_permission field of all documents - is that expected behavior?

I have enable_document_permission set to Yes

**Comment by catmanjan** [comment]
@praveen-elastic Connector Owner isn’t a group in SharePoint though, or is this the same thing as Site Owner?

I thought maybe the Connector Owners was a workplace search concept

**Comment by praveen-elastic** [comment]
Hey @catmanjan, I think I am a bit confused. Let to give you a high-level overview of how permissions are synced. 

First step: the connector creates a mapping of SharePoint to Workplace user using a mapping csv present in the directory which specifies what's the name of the SharePoint user in Workplace Search. If a mapping csv is not present, it takes the name of SharePoint user to be same in Workplace Search.

Second Step: The connector fetches all the user_ids from SharePoint and maps them to the Workplace Search user names according to the mapping file. If the mapping for that SharePoint user is absent, the connector takes the name of that user same in Workplace Search. 

Final Step: For each user_id we fetch the list of permissions assigned to it in SharePoint and then call `add_permission` api with this list of permissions and the mapped name in Workplace Search. 

Coming to document level permission: These are added at the time of full sync/ incremental sync. Each document will contain `_allow_permission` that contains a list of permissions added to that object in SharePoint, if enable_document_permission is set to Yes. 

Hope this helps. If not can you tell me what is `Connector Owners` referring to ? Is that the SharePoint User name ?

**Comment by catmanjan** [comment]
Yeah that was my understanding of the process too - here is a screenshot of the _allow_permissions against a document

I can see the Sharepoint usernames I'm expecting, but they also have these other permissions (circled in red)

![image](https://user-images.githubusercontent.com/137350/168048887-d64b8987-e2de-41ab-b06b-4501d861ab8d.png)

Where do these permissions come from, and is it expected that all my users would have Connector Owner and therefore be able to see all the document?

**Comment by praveen-elastic** [comment]
These are default groups created in your SharePoint. 
Permissions in SharePoint are assigned to users via groups. 
I have attached an image which shows the Permissions assigned to a SharePoint library for a site-collection named: 'Enterprise Search'
![image](https://user-images.githubusercontent.com/90465691/168050154-302dbe6f-dc9a-438e-b42e-f1629fa245f7.png)

**Comment by catmanjan** [comment]
Ah I see, so it makes sense that all the documents under this site would have this as a required permission, thanks
