### ISSUE TITLE
Test instance is running but _api endpoint not working 

### ISSUE THREAD

**Issue by danajuratoni** [elastic/enterprise-search-sharepoint-server-connector#52]
Hi Team,

The host URL of your SharePoint Server is up and running, but the _api endpoint used by the connector package is not working.
I get 

> ERROR    test_connectivity:sharepoint_client.py:79 Error while fetching from the sharepoint, url: http://{hostUrl}:8491///sites/enterprise/_api/web/webs?&$skip=0&$top=5000. Retry Count: 3. Error: Internal Server Error

I used the configs shared in this Slack thread https://elastic.slack.com/archives/C02AV5C8ZDE/p1650305377937579?thread_ts=1649696861.738989&cid=C02AV5C8ZDE

**Comment by praveen-elastic** [comment]
Hey @danajuratoni, I looked into it and found that the problem stemmed from the SharePoint server and not the code. 
I believe it has been fixed now. Let me know if it still does not work for you.

**Comment by serenachou** [comment]
per Dana this is working, we can close this
