### ISSUE TITLE
Metadata is missing and url is not clickable in Workplace Search

### ISSUE THREAD

**Issue by praveen-elastic** [elastic/enterprise-search-sharepoint-server-connector#55]
Issue posted by @rajaseg. Link not clickable and missing metadata of the file
![174158340-5559e261-ee30-4111-8c4d-e7d609db9378](https://user-images.githubusercontent.com/90465691/174272403-ac544d6e-13ef-4ced-b6b0-738d41329c25.png)

It should show metadata like the below image. The link is clickable here.
![174158481-0e65025a-1bb3-4489-b819-2877f136f069](https://user-images.githubusercontent.com/90465691/174272495-b3d61a54-b218-40e1-a23d-6d946bcd5407.png)

**Comment by moxarth-elastic** [comment]
Hey @rajaseg, it looks like you've created the content source from the UI but you haven't added the fields from the display settings. If you create content source from the UI, as the next step, you need to configure the fields you wish to see in the result. If you'll create the content source from the bootstrap command, you should see the fields on the search result. We recommend creating content source from bootstrap command.

**Comment by rajaseg** [comment]
> 

@moxarth-elastic, Sorry for the late reply. I am a bit busy.

Yes, I was able to enable the required fields from the display settings. Everything looks good.

One more question on the network connector. We enabled the link for the files. But unable to open them. Am I doing anything wrong?

**Comment by moxarth-elastic** [comment]
@rajaseg Glad to hear you were able to get the results. For the network connector, the url will only work if the network drive/shared drive is mapped in your system where you are accessing the Enterprise Search instance through browser. If you are accessing it on Windows, you can map the network drive in file explorer by following this [link](https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d). For MacOS you need to do so via finder, you can follow the steps given [here](https://setapp.com/how-to/map-a-network-drive-on-mac#:~:text=In%20Finder%2C%20either%20hit%20Command,to%20mount%20the%20network%20drive).

**Comment by rajaseg** [comment]
> @rajaseg Glad to hear you were able to get the results. For the network connector, the url will only work if the network drive/shared drive is mapped in your system where you are accessing the Enterprise Search instance through browser. If you are accessing it on Windows, you can map the network drive in file explorer by following this [link](https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d). For MacOS you need to do so via finder, you can follow the steps given [here](https://setapp.com/how-to/map-a-network-drive-on-mac#:~:text=In%20Finder%2C%20either%20hit%20Command,to%20mount%20the%20network%20drive).

Hi @moxarth-elastic Let me try your recommendations.

**Comment by rajaseg** [comment]
> > > @rajaseg Glad to hear you were able to get the results. For the network connector, the url will only work if the network drive/shared drive is mapped in your system where you are accessing the Enterprise Search instance through browser. If you are accessing it on Windows, you can map the network drive in file explorer by following this [link](https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d). For MacOS you need to do so via finder, you can follow the steps given [here](https://setapp.com/how-to/map-a-network-drive-on-mac#:~:text=In%20Finder%2C%20either%20hit%20Command,to%20mount%20the%20network%20drive).
> > 
> > 
> > Hi @moxarth-elastic Let me try your recommendations.
> 
> Sure @rajaseg, let me know if you'll have any queries.

@moxarth-elastic, Everything working as expected. You can close the issue.

I have a small query related to SharePoint Online, is it possible to mention a specific site collection to crawl in the settings? The connector requires tenant-level approval makes it critical to configure department-level site collections. Normally department-level site collection admins wouldn't have tenant-level permissions to approve. It would be good to narrow down the permissions.

**Comment by moxarth-elastic** [comment]
> 

Sounds great!
@rajaseg, Sharepoint Online repository is managed by other set of Elastic Team. Tagging @artem-shelkovnikov here to look into this.

**Comment by serenachou** [comment]
@rajaseg  in Enterprise Search 8.3 this is possible to filter based on site in SharePoint Online. see the note on breaking changes -> https://www.elastic.co/guide/en/enterprise-search/current/release-notes-8.3.0.html

**Comment by rajaseg** [comment]
> @rajaseg in Enterprise Search 8.3 this is possible to filter based on site in SharePoint Online. see the note on breaking changes -> https://www.elastic.co/guide/en/enterprise-search/current/release-notes-8.3.0.html

@serenachou, Thank you very much for the reply.

The below URL mentioned `path_template` and `file_extention` for the applicable rules. Where to find the files? or how to configure them?

https://www.elastic.co/guide/en/workplace-search/8.3/workplace-search-sharepoint-online-connector.html#sharepoint-indexing-rules

**Comment by praveen-elastic** [comment]
Hi @rajaseg, if you want to configure these fields, you can follow the below URL.

https://www.elastic.co/guide/en/workplace-search/8.3/workplace-search-customizing-indexing-rules.html#updating-indexing-rules
