### ISSUE TITLE
[Bug] Links in Enterprise Search search application lead to 404s

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/enterprise-search-sharepoint-server-connector#65]
When content is ingested from Sharepoint Server and then is searched on, clicking on results of search from Sharepoint Server lead to 404 pages.

Steps to reproduce:
1. Ingest data from Sharepoint Server into Enterprise Search
2. Click on "Go to search application" in Workplace Search admin
3. Search for something that produces results from the ingested instance
4. Click on any item

Expected:
Redirect happens to a valid URL

Actual:
Redirect happens to a page that shows 404

Screenshots:

![image](https://user-images.githubusercontent.com/12238374/204337919-f56e09b2-021b-4933-9b77-43cc7027d82c.png)

![image](https://user-images.githubusercontent.com/12238374/204337942-dd7a3c1a-5a86-4d1f-a5fd-bea73e0f237d.png)

**Comment by prashant-elastic** [comment]
Hey, we have tried to index the data by adding a list with a list-item in the SharePoint server. On the workplace search instance when we clicked the url of the respective list and list-item and it successfully redirected to the SharePoint instance. 
I however found that the url of hidden Sharepoint objects are not accessible. Hence, objects such as Composed Looks, Converted Forms, etc. that are hidden from the user will return 404. 
This is not the case with user defined Sharepoint objects. Please confirm this at your end.

**Comment by danajuratoni** [comment]
Removing the link for unavailable objects seems to be the most straightforward path, please also document this as expected behavior.

**Comment by praveen-elastic** [comment]
Sure, I would suggest removing the hidden objects(lists such as Composed Looks, Master Page Gallery) from being indexed as well since the hidden objects are not user's data and the metadata is not at all relevant to them. These hidden lists are are a part of SharePoint server itself. Let me know and I'll raise a PR soon.

**Comment by danajuratoni** [comment]
>I would suggest removing the hidden objects from being indexed as well 

Considering the user has no access to this data anyway, this sounds reasonable.
